// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: erh_engine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ERHEngine_Evaluate_FullMethodName = "/erh_engine.ERHEngine/Evaluate"
	ERHEngine_Health_FullMethodName   = "/erh_engine.ERHEngine/Health"
)

// ERHEngineClient is the client API for ERHEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Mirrors erh_engine.contracts.schemas field-for-field. The gRPC path is the
// low-latency channel used by the Kubernetes sidecar and the Go/Gin edge proxy.
type ERHEngineClient interface {
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type eRHEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewERHEngineClient(cc grpc.ClientConnInterface) ERHEngineClient {
	return &eRHEngineClient{cc}
}

func (c *eRHEngineClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, ERHEngine_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRHEngineClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ERHEngine_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ERHEngineServer is the server API for ERHEngine service.
// All implementations must embed UnimplementedERHEngineServer
// for forward compatibility.
//
// Mirrors erh_engine.contracts.schemas field-for-field. The gRPC path is the
// low-latency channel used by the Kubernetes sidecar and the Go/Gin edge proxy.
type ERHEngineServer interface {
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedERHEngineServer()
}

// UnimplementedERHEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedERHEngineServer struct{}

func (UnimplementedERHEngineServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedERHEngineServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedERHEngineServer) mustEmbedUnimplementedERHEngineServer() {}
func (UnimplementedERHEngineServer) testEmbeddedByValue()                   {}

// UnsafeERHEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ERHEngineServer will
// result in compilation errors.
type UnsafeERHEngineServer interface {
	mustEmbedUnimplementedERHEngineServer()
}

func RegisterERHEngineServer(s grpc.ServiceRegistrar, srv ERHEngineServer) {
	// If the following call panics, it indicates UnimplementedERHEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ERHEngine_ServiceDesc, srv)
}

func _ERHEngine_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERHEngineServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERHEngine_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERHEngineServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERHEngine_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERHEngineServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERHEngine_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERHEngineServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ERHEngine_ServiceDesc is the grpc.ServiceDesc for ERHEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ERHEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "erh_engine.ERHEngine",
	HandlerType: (*ERHEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _ERHEngine_Evaluate_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ERHEngine_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "erh_engine.proto",
}
