// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: erh_engine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sample struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Complexity float64                `protobuf:"fixed64,2,opt,name=complexity,proto3" json:"complexity,omitempty"`
	Value      float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Judgment   float64                `protobuf:"fixed64,4,opt,name=judgment,proto3" json:"judgment,omitempty"`
	Weight     float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	// JSON-encoded context object (kept opaque on the wire).
	ContextJson   string `protobuf:"bytes,6,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_erh_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_erh_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_erh_engine_proto_rawDescGZIP(), []int{0}
}

func (x *Sample) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sample) GetComplexity() float64 {
	if x != nil {
		return x.Complexity
	}
	return 0
}

func (x *Sample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Sample) GetJudgment() float64 {
	if x != nil {
		return x.Judgment
	}
	return 0
}

func (x *Sample) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Sample) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

type EvaluateParams struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Tau                  float64                `protobuf:"fixed64,1,opt,name=tau,proto3" json:"tau,omitempty"`
	C                    float64                `protobuf:"fixed64,2,opt,name=C,proto3" json:"C,omitempty"`
	Epsilon              float64                `protobuf:"fixed64,3,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	SlackFactor          float64                `protobuf:"fixed64,4,opt,name=slack_factor,json=slackFactor,proto3" json:"slack_factor,omitempty"`
	AllowedViolationRate float64                `protobuf:"fixed64,5,opt,name=allowed_violation_rate,json=allowedViolationRate,proto3" json:"allowed_violation_rate,omitempty"`
	Baseline             string                 `protobuf:"bytes,6,opt,name=baseline,proto3" json:"baseline,omitempty"`
	ImportanceQuantile   float64                `protobuf:"fixed64,7,opt,name=importance_quantile,json=importanceQuantile,proto3" json:"importance_quantile,omitempty"`
	XMax                 int32                  `protobuf:"varint,8,opt,name=x_max,json=xMax,proto3" json:"x_max,omitempty"` // 0 => auto
	IncludeCurves        bool                   `protobuf:"varint,9,opt,name=include_curves,json=includeCurves,proto3" json:"include_curves,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EvaluateParams) Reset() {
	*x = EvaluateParams{}
	mi := &file_erh_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateParams) ProtoMessage() {}

func (x *EvaluateParams) ProtoReflect() protoreflect.Message {
	mi := &file_erh_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateParams.ProtoReflect.Descriptor instead.
func (*EvaluateParams) Descriptor() ([]byte, []int) {
	return file_erh_engine_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateParams) GetTau() float64 {
	if x != nil {
		return x.Tau
	}
	return 0
}

func (x *EvaluateParams) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *EvaluateParams) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *EvaluateParams) GetSlackFactor() float64 {
	if x != nil {
		return x.SlackFactor
	}
	return 0
}

func (x *EvaluateParams) GetAllowedViolationRate() float64 {
	if x != nil {
		return x.AllowedViolationRate
	}
	return 0
}

func (x *EvaluateParams) GetBaseline() string {
	if x != nil {
		return x.Baseline
	}
	return ""
}

func (x *EvaluateParams) GetImportanceQuantile() float64 {
	if x != nil {
		return x.ImportanceQuantile
	}
	return 0
}

func (x *EvaluateParams) GetXMax() int32 {
	if x != nil {
		return x.XMax
	}
	return 0
}

func (x *EvaluateParams) GetIncludeCurves() bool {
	if x != nil {
		return x.IncludeCurves
	}
	return false
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*Sample              `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	Params        *EvaluateParams        `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	JudgeName     string                 `protobuf:"bytes,3,opt,name=judge_name,json=judgeName,proto3" json:"judge_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_erh_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_erh_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_erh_engine_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateRequest) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *EvaluateRequest) GetParams() *EvaluateParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *EvaluateRequest) GetJudgeName() string {
	if x != nil {
		return x.JudgeName
	}
	return ""
}

type PrimeRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Complexity    float64                `protobuf:"fixed64,2,opt,name=complexity,proto3" json:"complexity,omitempty"`
	Delta         float64                `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	ContextJson   string                 `protobuf:"bytes,5,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimeRef) Reset() {
	*x = PrimeRef{}
	mi := &file_erh_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeRef) ProtoMessage() {}

func (x *PrimeRef) ProtoReflect() protoreflect.Message {
	mi := &file_erh_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeRef.ProtoReflect.Descriptor instead.
func (*PrimeRef) Descriptor() ([]byte, []int) {
	return file_erh_engine_proto_rawDescGZIP(), []int{3}
}

func (x *PrimeRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrimeRef) GetComplexity() float64 {
	if x != nil {
		return x.Complexity
	}
	return 0
}

func (x *PrimeRef) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *PrimeRef) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PrimeRef) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

type Curve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             []float64              `protobuf:"fixed64,1,rep,packed,name=x,proto3" json:"x,omitempty"`
	Y             []float64              `protobuf:"fixed64,2,rep,packed,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Curve) Reset() {
	*x = Curve{}
	mi := &file_erh_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Curve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Curve) ProtoMessage() {}

func (x *Curve) ProtoReflect() protoreflect.Message {
	mi := &file_erh_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Curve.ProtoReflect.Descriptor instead.
func (*Curve) Descriptor() ([]byte, []int) {
	return file_erh_engine_proto_rawDescGZIP(), []int{4}
}

func (x *Curve) GetX() []float64 {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *Curve) GetY() []float64 {
	if x != nil {
		return x.Y
	}
	return nil
}

type EvaluateResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ErhSatisfied      bool                   `protobuf:"varint,1,opt,name=erh_satisfied,json=erhSatisfied,proto3" json:"erh_satisfied,omitempty"`
	RiskScore         float64                `protobuf:"fixed64,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	ViolationRate     float64                `protobuf:"fixed64,3,opt,name=violation_rate,json=violationRate,proto3" json:"violation_rate,omitempty"`
	MaxRatio          float64                `protobuf:"fixed64,4,opt,name=max_ratio,json=maxRatio,proto3" json:"max_ratio,omitempty"`
	BoundValue        float64                `protobuf:"fixed64,5,opt,name=bound_value,json=boundValue,proto3" json:"bound_value,omitempty"`
	EstimatedExponent float64                `protobuf:"fixed64,6,opt,name=estimated_exponent,json=estimatedExponent,proto3" json:"estimated_exponent,omitempty"`
	RSquared          float64                `protobuf:"fixed64,7,opt,name=r_squared,json=rSquared,proto3" json:"r_squared,omitempty"`
	NumSamples        int32                  `protobuf:"varint,8,opt,name=num_samples,json=numSamples,proto3" json:"num_samples,omitempty"`
	NumPrimes         int32                  `protobuf:"varint,9,opt,name=num_primes,json=numPrimes,proto3" json:"num_primes,omitempty"`
	BoundType         string                 `protobuf:"bytes,10,opt,name=bound_type,json=boundType,proto3" json:"bound_type,omitempty"`
	JudgeName         string                 `protobuf:"bytes,11,opt,name=judge_name,json=judgeName,proto3" json:"judge_name,omitempty"`
	Primes            []*PrimeRef            `protobuf:"bytes,12,rep,name=primes,proto3" json:"primes,omitempty"`
	PiCurve           *Curve                 `protobuf:"bytes,13,opt,name=pi_curve,json=piCurve,proto3" json:"pi_curve,omitempty"`
	ErrorCurve        *Curve                 `protobuf:"bytes,14,opt,name=error_curve,json=errorCurve,proto3" json:"error_curve,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_erh_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_erh_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_erh_engine_proto_rawDescGZIP(), []int{5}
}

func (x *EvaluateResponse) GetErhSatisfied() bool {
	if x != nil {
		return x.ErhSatisfied
	}
	return false
}

func (x *EvaluateResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *EvaluateResponse) GetViolationRate() float64 {
	if x != nil {
		return x.ViolationRate
	}
	return 0
}

func (x *EvaluateResponse) GetMaxRatio() float64 {
	if x != nil {
		return x.MaxRatio
	}
	return 0
}

func (x *EvaluateResponse) GetBoundValue() float64 {
	if x != nil {
		return x.BoundValue
	}
	return 0
}

func (x *EvaluateResponse) GetEstimatedExponent() float64 {
	if x != nil {
		return x.EstimatedExponent
	}
	return 0
}

func (x *EvaluateResponse) GetRSquared() float64 {
	if x != nil {
		return x.RSquared
	}
	return 0
}

func (x *EvaluateResponse) GetNumSamples() int32 {
	if x != nil {
		return x.NumSamples
	}
	return 0
}

func (x *EvaluateResponse) GetNumPrimes() int32 {
	if x != nil {
		return x.NumPrimes
	}
	return 0
}

func (x *EvaluateResponse) GetBoundType() string {
	if x != nil {
		return x.BoundType
	}
	return ""
}

func (x *EvaluateResponse) GetJudgeName() string {
	if x != nil {
		return x.JudgeName
	}
	return ""
}

func (x *EvaluateResponse) GetPrimes() []*PrimeRef {
	if x != nil {
		return x.Primes
	}
	return nil
}

func (x *EvaluateResponse) GetPiCurve() *Curve {
	if x != nil {
		return x.PiCurve
	}
	return nil
}

func (x *EvaluateResponse) GetErrorCurve() *Curve {
	if x != nil {
		return x.ErrorCurve
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_erh_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_erh_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_erh_engine_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_erh_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_erh_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_erh_engine_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_erh_engine_proto protoreflect.FileDescriptor

const file_erh_engine_proto_rawDesc = "" +
	"\n" +
	"\x10erh_engine.proto\x12\n" +
	"erh_engine\"\xa5\x01\n" +
	"\x06Sample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"complexity\x18\x02 \x01(\x01R\n" +
	"complexity\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1a\n" +
	"\bjudgment\x18\x04 \x01(\x01R\bjudgment\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x12!\n" +
	"\fcontext_json\x18\x06 \x01(\tR\vcontextJson\"\xac\x02\n" +
	"\x0eEvaluateParams\x12\x10\n" +
	"\x03tau\x18\x01 \x01(\x01R\x03tau\x12\f\n" +
	"\x01C\x18\x02 \x01(\x01R\x01C\x12\x18\n" +
	"\aepsilon\x18\x03 \x01(\x01R\aepsilon\x12!\n" +
	"\fslack_factor\x18\x04 \x01(\x01R\vslackFactor\x124\n" +
	"\x16allowed_violation_rate\x18\x05 \x01(\x01R\x14allowedViolationRate\x12\x1a\n" +
	"\bbaseline\x18\x06 \x01(\tR\bbaseline\x12/\n" +
	"\x13importance_quantile\x18\a \x01(\x01R\x12importanceQuantile\x12\x13\n" +
	"\x05x_max\x18\b \x01(\x05R\x04xMax\x12%\n" +
	"\x0einclude_curves\x18\t \x01(\bR\rincludeCurves\"\x92\x01\n" +
	"\x0fEvaluateRequest\x12,\n" +
	"\asamples\x18\x01 \x03(\v2\x12.erh_engine.SampleR\asamples\x122\n" +
	"\x06params\x18\x02 \x01(\v2\x1a.erh_engine.EvaluateParamsR\x06params\x12\x1d\n" +
	"\n" +
	"judge_name\x18\x03 \x01(\tR\tjudgeName\"\x8b\x01\n" +
	"\bPrimeRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"complexity\x18\x02 \x01(\x01R\n" +
	"complexity\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\x12!\n" +
	"\fcontext_json\x18\x05 \x01(\tR\vcontextJson\"#\n" +
	"\x05Curve\x12\f\n" +
	"\x01x\x18\x01 \x03(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x03(\x01R\x01y\"\x95\x04\n" +
	"\x10EvaluateResponse\x12#\n" +
	"\rerh_satisfied\x18\x01 \x01(\bR\ferhSatisfied\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x01R\triskScore\x12%\n" +
	"\x0eviolation_rate\x18\x03 \x01(\x01R\rviolationRate\x12\x1b\n" +
	"\tmax_ratio\x18\x04 \x01(\x01R\bmaxRatio\x12\x1f\n" +
	"\vbound_value\x18\x05 \x01(\x01R\n" +
	"boundValue\x12-\n" +
	"\x12estimated_exponent\x18\x06 \x01(\x01R\x11estimatedExponent\x12\x1b\n" +
	"\tr_squared\x18\a \x01(\x01R\brSquared\x12\x1f\n" +
	"\vnum_samples\x18\b \x01(\x05R\n" +
	"numSamples\x12\x1d\n" +
	"\n" +
	"num_primes\x18\t \x01(\x05R\tnumPrimes\x12\x1d\n" +
	"\n" +
	"bound_type\x18\n" +
	" \x01(\tR\tboundType\x12\x1d\n" +
	"\n" +
	"judge_name\x18\v \x01(\tR\tjudgeName\x12,\n" +
	"\x06primes\x18\f \x03(\v2\x14.erh_engine.PrimeRefR\x06primes\x12,\n" +
	"\bpi_curve\x18\r \x01(\v2\x11.erh_engine.CurveR\apiCurve\x122\n" +
	"\verror_curve\x18\x0e \x01(\v2\x11.erh_engine.CurveR\n" +
	"errorCurve\"\x0f\n" +
	"\rHealthRequest\"\\\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\x93\x01\n" +
	"\tERHEngine\x12E\n" +
	"\bEvaluate\x12\x1b.erh_engine.EvaluateRequest\x1a\x1c.erh_engine.EvaluateResponse\x12?\n" +
	"\x06Health\x12\x19.erh_engine.HealthRequest\x1a\x1a.erh_engine.HealthResponseb\x06proto3"

var (
	file_erh_engine_proto_rawDescOnce sync.Once
	file_erh_engine_proto_rawDescData []byte
)

func file_erh_engine_proto_rawDescGZIP() []byte {
	file_erh_engine_proto_rawDescOnce.Do(func() {
		file_erh_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_erh_engine_proto_rawDesc), len(file_erh_engine_proto_rawDesc)))
	})
	return file_erh_engine_proto_rawDescData
}

var file_erh_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_erh_engine_proto_goTypes = []any{
	(*Sample)(nil),           // 0: erh_engine.Sample
	(*EvaluateParams)(nil),   // 1: erh_engine.EvaluateParams
	(*EvaluateRequest)(nil),  // 2: erh_engine.EvaluateRequest
	(*PrimeRef)(nil),         // 3: erh_engine.PrimeRef
	(*Curve)(nil),            // 4: erh_engine.Curve
	(*EvaluateResponse)(nil), // 5: erh_engine.EvaluateResponse
	(*HealthRequest)(nil),    // 6: erh_engine.HealthRequest
	(*HealthResponse)(nil),   // 7: erh_engine.HealthResponse
}
var file_erh_engine_proto_depIdxs = []int32{
	0, // 0: erh_engine.EvaluateRequest.samples:type_name -> erh_engine.Sample
	1, // 1: erh_engine.EvaluateRequest.params:type_name -> erh_engine.EvaluateParams
	3, // 2: erh_engine.EvaluateResponse.primes:type_name -> erh_engine.PrimeRef
	4, // 3: erh_engine.EvaluateResponse.pi_curve:type_name -> erh_engine.Curve
	4, // 4: erh_engine.EvaluateResponse.error_curve:type_name -> erh_engine.Curve
	2, // 5: erh_engine.ERHEngine.Evaluate:input_type -> erh_engine.EvaluateRequest
	6, // 6: erh_engine.ERHEngine.Health:input_type -> erh_engine.HealthRequest
	5, // 7: erh_engine.ERHEngine.Evaluate:output_type -> erh_engine.EvaluateResponse
	7, // 8: erh_engine.ERHEngine.Health:output_type -> erh_engine.HealthResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_erh_engine_proto_init() }
func file_erh_engine_proto_init() {
	if File_erh_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_erh_engine_proto_rawDesc), len(file_erh_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_erh_engine_proto_goTypes,
		DependencyIndexes: file_erh_engine_proto_depIdxs,
		MessageInfos:      file_erh_engine_proto_msgTypes,
	}.Build()
	File_erh_engine_proto = out.File
	file_erh_engine_proto_goTypes = nil
	file_erh_engine_proto_depIdxs = nil
}
