#!/usr/bin/env python3
"""
Update LaTeX thesis with numerical results from simulation.

This script reads the results summary file generated by the simulation
and injects the values into the LaTeX thesis file, replacing placeholders.
"""

import re
import os
import sys

def parse_results_summary(file_path):
    """Parse the results summary text file into a structured dictionary."""
    if not os.path.exists(file_path):
        print(f"Error: Results summary file not found at {file_path}")
        sys.exit(1)

    with open(file_path, 'r') as f:
        content = f.read()

    results = {}
    current_judge = None

    # Iterate through lines to parse judge sections
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        # Check for new judge section (e.g., "Biased Judge:")
        judge_match = re.match(r"^(.+) Judge:$", line)
        if judge_match:
            current_judge = judge_match.group(1)
            results[current_judge] = {}
            continue

        if current_judge:
            # Parse metrics (e.g., "Mistake rate: 0.123")
            metric_match = re.match(r"^([^:]+):\s+(.+)$", line)
            if metric_match:
                key = metric_match.group(1).strip()
                value = metric_match.group(2).strip()
                results[current_judge][key] = value

    return results

def update_latex_file(latex_path, results):
    """Update the LaTeX file with parsed results."""
    if not os.path.exists(latex_path):
        print(f"Error: LaTeX file not found at {latex_path}")
        sys.exit(1)

    with open(latex_path, 'r') as f:
        content = f.read()

    # Mapping from LaTeX section name to Results key
    # LaTeX uses \subsubsection{BiasedJudge} -> Results uses "Biased"
    judge_mapping = {
        'BiasedJudge': 'Biased',
        'NoisyJudge': 'Noisy',
        'ConservativeJudge': 'Conservative',
        'RadicalJudge': 'Radical'
    }

    updated_content = content

    for latex_name, result_key in judge_mapping.items():
        if result_key not in results:
            print(f"Warning: No results found for {result_key}")
            continue
            
        judge_data = results[result_key]
        
        # We need to find the specific section for this judge to avoid replacing 
        # [TBD] in other sections with the wrong values.
        # We search for the subsection and then limit the replacement to the text block following it.
        
        # Regex to find the block starting with \subsubsection{Name} until the next \subsubsection or end
        section_pattern = re.compile(
            r"(\\subsubsection\{" + re.escape(latex_name) + r"\}.*?)(?=\\subsubsection|\Z)", 
            re.DOTALL
        )
        
        match = section_pattern.search(updated_content)
        if not match:
            print(f"Warning: Could not find section for {latex_name}")
            continue
            
        section_text = match.group(1)
        new_section_text = section_text
        
        # Replace placeholders in this section
        # Mistake rate: [TBD]%
        new_section_text = re.sub(
            r"Mistake rate: \[TBD\]\\%", 
            f"Mistake rate: {float(judge_data.get('Mistake rate', 0))*100:.1f}\\%", 
            new_section_text
        )
        
        # Number of ethical primes: [TBD]
        new_section_text = re.sub(
            r"Number of ethical primes: \[TBD\]", 
            f"Number of ethical primes: {judge_data.get('Ethical primes', 'N/A')}", 
            new_section_text
        )
        
        # Estimated exponent: \alpha = [TBD]
        new_section_text = re.sub(
            r"Estimated exponent: \\alpha = \[TBD\]", 
            f"Estimated exponent: \\\\alpha = {judge_data.get('Estimated exponent', 'N/A')}", 
            new_section_text
        )
        
        # ERH satisfied: [YES/NO] or [TBD]
        erh_val = judge_data.get('ERH satisfied', 'No')
        erh_text = "Yes" if "Yes" in erh_val else "No"
        new_section_text = re.sub(
            r"ERH satisfied: \[(?:YES/NO|TBD)\]", 
            f"ERH satisfied: {erh_text}", 
            new_section_text
        )
        
        # Update the main content
        updated_content = updated_content.replace(section_text, new_section_text)
        print(f"Updated section for {latex_name}")

    with open(latex_path, 'w') as f:
        f.write(updated_content)
    
    print(f"Successfully updated {latex_path}")

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    results_path = os.path.join(base_dir, "simulation", "output", "results_summary.txt")
    latex_path = os.path.join(base_dir, "ethical_riemann_hypothesis.tex")
    
    print(f"Reading results from: {results_path}")
    results = parse_results_summary(results_path)
    
    print(f"Updating LaTeX file: {latex_path}")
    update_latex_file(latex_path, results)

